name: tachidesk_sorayomi
description: A new Flutter frontend for Tachidesk.

publish_to: "none"
version: 0.5.10+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.3
  cached_network_image: ^3.3.1
  cached_network_image_platform_interface: ^4.0.0
  cupertino_icons: ^1.0.5
  dio: ^5.4.0
  dio_cache_interceptor: ^3.4.0
  dio_cache_interceptor_hive_store: ^3.2.1
  equatable: ^2.0.5
  file_picker: ^5.2.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_cache_manager: ^3.3.0
  flutter_hooks: ^0.20.0
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.2.5
  font_awesome_flutter: ^10.2.1
  freezed_annotation: ^2.2.0
  get: ^4.6.6
  go_router: ^10.0.0
  google_fonts: ^6.2.1
  hooks_riverpod: ^2.1.1
  http_parser: ^4.0.2
  image_picker: ^1.0.7
  infinite_scroll_pagination: ^3.2.0
  intl: ^0.19.0
  json_annotation: ^4.8.1
  mime: ^1.0.4
  network_info_plus: ^4.0.0
  package_info_plus: ^4.0.0
  path: ^1.8.3
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  pub_semver: ^2.1.2
  queue: ^3.1.0+2
  riverpod_annotation: ^2.0.0
  scrollable_positioned_list: ^0.3.5
  shared_preferences: ^2.0.15
  url_launcher: ^6.2.4
  web_socket_channel: ^2.2.0

dev_dependencies:
  build_runner: ^2.3.2
  # flutter_flavorizr: ^2.1.5
  flutter_gen_runner: ^5.1.0+1
  flutter_launcher_icons: ^0.13.0
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.14
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  go_router_builder: ^2.0.0
  json_serializable: ^6.5.4
  lints: ^2.0.1
  riverpod_generator: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/icons/launcher/
    - assets/icons/datetime.png
    - assets/icons/user_profile.png
    - assets/icons/calendar.png
    - assets/icons/tasks.png
    - assets/icons/checker.png
    - assets/icons/folder.png
    - assets/icons/user.png
    - assets/images/bg2.jpg
    - assets/images/background.jpg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          style: normal

flutter_gen:
  output: lib/src/constants/gen/

flutter_native_splash:
  color: "#54C5F8"
  image: assets/icons/dark_icon.png
  branding: assets/icons/launcher/from_suwayomi.png
  color_dark: "#01579B"
  image_dark: assets/icons/light_icon.png
  android_12:
    color: "#54C5F8"
    color_dark: "#01579B"
    icon_background_color: "#54C5F8"
    icon_background_color_dark: "#01579B"
    image: assets/icons/dark_icon.png
    image_dark: assets/icons/light_icon.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/launcher/sorayomi_icon.png"
  web:
    generate: true
    image_path: "assets/icons/launcher/sorayomi_icon.png"
    background_color: "#54C5F8"
    theme_color: "#54C5F8"
  windows:
    generate: true
    image_path: "assets/icons/launcher/sorayomi_icon.png"
  macos:
    generate: true
    image_path: "assets/icons/launcher/sorayomi_icon.png"
